### PR TITLE
basic fix for dupe bug

### PR DESCRIPTION
**Pull request by Carter4242**
https://github.com/BenCodez/GraveStonesPlus/issues/33

### CODE REVIEW

**Comment by BenCodez** [comment]
grave.claim already calls removegrave. Shouldn't make any difference calling it twice. Have you tested if it makes a difference?

**Comment by Carter4242** [comment]
sorry writing actual fix now - how do I build this? Via Maven?

**Comment by Carter4242** [comment]
btw can confirm the issue is real, my server members also found it independently.

**Comment by BenCodez** [comment]
use maven

**Comment by Carter4242** [comment]
this also doesn't work. Maybe come back in an hour and see if I fixed it my bad.

**Comment by BenCodez** [comment]
Try what I said on the original issue?

**Comment by Carter4242** [comment]
I am on the latest version from your link, I am using display entities as well. This only occurs if players can get player heads from another source.

**Comment by BenCodez** [comment]
> I am on the latest version from your link, I am using display entities as well. This only occurs if players can get player heads from another source.

What happens if you don't use display entities? What other source are you getting heads from?

**Comment by Carter4242** [comment]
Players can get heads from another plugin on the server. The same error occurs when not using display entities.

**Comment by Carter4242** [comment]
@BenCodez I'm sorry I was having difficulty building because of the updates you pushed like 4 days ago (that broke the local building for some reason). I can confirm that the change I pushed **does** work. I moved it out of the check owner if statement to its own. Obviously, it's not ideal to do things this way, but if you have a method of obtaining PLAYER_HEADs this would be required to prevent duping.

**Comment by BenCodez** [comment]
https://github.com/BenCodez/GraveStonesPlus/commit/33e0a6794d20d1b25210aa3c433fd3be2b2ffd1a

https://bencodez.com/job/GraveStonesPlus/

Should be good now

**Pull request closed without merging**
